#!/bin/env bash

# Array of project names
projects=(
    "Random Quote Generator"
    "Countdown Timer"
    "Palindrome Checker"
    "FizzBuzz"
    "Tip Calculator"
    "Basic Calculator"
    "Temperature Converter"
    "Reverse a String"
    "Word Count Tool"
    "Character Counter"
    "BMI Calculator"
    "To-do List"
    "Array Sorting"
    "Vowel Counter"
    "Number Guessing Game"
    "Leap Year Checker"
    "Random Background Color"
    "Dice Roll Simulator"
    "Grocery List"
    "Factorial Calculator"
    "Even or Odd Number Checker"
    "Multiplication Table Generator"
    "Random Password Generator"
    "Email Validator"
    "Prime Number Checker"
    "Image Slider"
    "Weather App"
    "Currency Converter"
    "Quiz App"
    "Drum Kit"
    "Form Validation"
    "Stopwatch"
    "Clock"
    "Tic-Tac-Toe"
    "Weather App with Geolocation"
    "Word Scramble Game"
    "Simple Chat App (Local)"
    "Rock, Paper, Scissors Game"
    "Shopping Cart"
    "LocalStorage To-Do App"
    "Movie Database Search"
    "Simple API Fetch"
    "Random User Generator"
    "Notes App"
    "Markdown Previewer"
    "Expense Tracker"
    "Temperature Fetcher"
    "Infinite Scrolling"
    "Memory Game"
    "Hex Color Generator"
    "Battleship Game"
    "Typing Speed Test"
    "Multi-step Form"
    "Online Code Editor"
    "Canvas Drawing App"
    "Image Gallery with Search"
    "Minesweeper"
    "Weather Dashboard"
    "Simple Kanban Board"
    "Image Filter App"
    "Virtual Keyboard"
    "Pong Game"
    "2048 Game"
    "Flight Search Tool"
    "Pomodoro Timer"
    "Expense Tracker with Charts"
    "Maze Generator and Solver"
    "YouTube Video Player"
    "Sudoku Solver"
    "E-commerce Store"
    "GitHub Profile Finder"
    "Quiz App with Timer"
    "Spotify Song Search"
    "Basic AI Chatbot"
    "Drag and Drop Upload"
    "Task Manager with Notifications"
    "Task Tracker with GraphQL"
    "Currency Conversion Chart"
    "Real-time Collaborative Drawing"
    "Calendar App"
    "Real-time Stock Tracker"
    "Twitter Clone (Basic)"
    "Tetris Game"
    "Simple Portfolio Builder"
    "Markdown Blog"
    "Music Player"
    "Image Compression Tool"
    "Speech Recognition App"
    "Real-time Chat App"
    "Expense Tracker with Firebase"
    "Chrome Extension"
    "GitHub Issue Tracker"
    "URL Shortener"
    "Real-time Weather App with Maps"
    "Crypto Price Tracker"
    "Interactive Story Game"
    "Task Tracker with Notifications"
    "Chess Game"
    "Progressive Web App (PWA)"
    "Real-time Multiplayer Game"
)

number=1

# Loop through each project and create the necessary files
for pj in "${projects[@]}"; do
    # Create the project directory
    project=$number.$pj
    mkdir "$project"

    # Create HTML, CSS, JS, and README files
    touch "$project/index.html"
    touch "$project/style.css"
    touch "$project/script.js"
    touch "$project/README.md"

    # Optionally, you can add basic content to the README.md
    echo "# $project" > "$project/README.md"
    echo "## Project Description" >> "$project/README.md"
    echo "A brief description of the project." >> "$project/README.md"
    echo "## Features" >> "$project/README.md"
    echo "- Feature 1" >> "$project/README.md"
    echo "- Feature 2" >> "$project/README.md"
    echo "## Technologies Used" >> "$project/README.md"
    echo "- HTML" >> "$project/README.md"
    echo "- CSS" >> "$project/README.md"
    echo "- JavaScript" >> "$project/README.md"
    echo "## Setup Instructions" >> "$project/README.md"
    echo "1. Clone the repository." >> "$project/README.md"
    echo "2. Open index.html in your browser." >> "$project/README.md"

    (( number++ ))
done

echo "Directories and files created successfully!"
